import { v4 as uuidv4 } from 'https://jspm.dev/uuid';

export let tweetsData = [   
    {
        handle: `@TrollBot66756542 💎`,
        profilePic: `images/troll.jpg`,
        likes: 27,
        retweets: 10,
        tweetText: `Buy Bitcoin, ETH Make 💰💰💰 low low prices. 
            Guaranteed return on investment. HMU DMs open!!`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: uuidv4(),
    },    
    {
        handle: `@Elon ✅`,
        profilePic: `images/musk.png`,
        likes: 6500,
        retweets: 234,
        tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
        replies: [
                  {
                handle: `@TomCruise ✅`,
                profilePic: `images/tcruise.png`,
                tweetText: `Yes! Sign me up! 😎🛩`,
                likes: 170,
                retweets: 53,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },
                  {
                handle: `@ChuckNorris ✅`,
                profilePic: `images/chucknorris.jpeg`,
                tweetText: `I went last year😴`,
                likes: 1520,
                retweets: 190,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4()
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
    },
        {
        handle: `@NoobCoder12`,
        profilePic: `images/flower.png`,
        likes: 10,
        retweets: 3,
        tweetText: `Are you a coder if you only know HTML?`,
        replies: [
            {
                handle: `@StackOverflower ☣️`,
                profilePic: `images/overflow.png`,
                tweetText: `No. Obviosuly not. Go get a job in McDonald's.`,
                likes: 1,
                retweets: 0,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/love.png`,
                tweetText: `You are wonderful just as you are! ❤️`,
                likes: 5,
                retweets: 1,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: uuidv4(),
    },
       
    {
        handle: `@B/R Football ✅`,
        profilePic: `images/rbfootball.jpg`,
        likes: 300,
        retweets: 70,
        tweetText: `When you get to be messi's bodyguard again`,
        replies: [
            {
                handle: `@Alex`,
                profilePic: `images/ballsoccer.jpg`,
                tweetText: `wow amazing`,
                likes: 0,
                retweets: 0,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },
            {
                handle: `@Savio`,
                profilePic: `images/messi.jpg`,
                tweetText: `when you are messi everyone loves you! ❤️`,
                likes: 5,
                retweets: 1,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },
            {
                handle: `@Emmanuel`,
                profilePic: `images/dog.jpg`,
                tweetText: `is Messi in need of another body guard`,
                likes: 1,
                retweets: 0,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },
            {
                handle: `@TipsyOdd`,
                profilePic: `images/ronaldo.jpg`,
                tweetText: `why is this funny`,
                likes: 0,
                retweets: 1,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },

        ],
        isLiked: false,
        isRetweeted: false,
        uuid: uuidv4(),
    },    
    {
        handle: `@NBA ✅`,
        profilePic: `images/basketball.jpg`,
        likes: 1000,
        retweets: 104,
        tweetText: `The NBA season is about to start`,
        replies: [
                  {
                handle: `@Mark `,
                profilePic: `images/kobi.jpg`,
                tweetText: `Can't wait`,
                likes: 1,
                retweets: 0,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },
                  {
                handle: `@ThisIsSmith ✅`,
                profilePic: `images/steph.jpg`,
                tweetText: `Lebron James is the best player`,
                likes: 50,
                retweets: 10,
                replies: [
                    {
                        handle: `@Ant123Nc `,
                        profilePic: `images/steph.jpg`,
                        tweetText: `I think it is Steph Curry`,
                        likes: 1,
                        retweets: 0,
                        replies: [],
                        isLiked: false,
                        isRetweeted: false,
                        uuid:uuidv4(),
                    }
                ],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4()
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: uuidv4(),
    },
        {
        handle: `@WWE ✅`,
        profilePic: `images/wwe.jpg`,
        likes: 122,
        retweets: 23,
        tweetText: `MondayNight Raw`,
        replies: [
            {
                handle: `@TheWrestlingFan`,
                profilePic: `images/moneyBank.jpg`,
                tweetText: `I cant wait`,
                likes: 1,
                retweets: 0,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },
            {
                handle: `@HugeFan`,
                profilePic: `images/cena.jpg`,
                tweetText: `I have been waiting for this day. YESSS`,
                likes: 0,
                retweets: 0,
                replies: [],
                isLiked: false,
                isRetweeted: false,
                uuid:uuidv4(),
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: uuidv4(),
    },
  
]